#server:
#  port: 8000

billing:
  kafka:
    message-group-name: billing-group-test
    order-created-topic: hw35.order.created-billing-test
    payment-executed-topic: hw35.payment.executed-test
    payment-rejected-topic: hw35.payment.rejected-test

spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/db_otus_35
    username: postgres
    password: postgres
#  flyway:
#    enabled: true
#    schemas: scheme
  kafka:
    bootstrap-servers: localhost:29092