#server:
#  port: 8000

billing:
  kafka:
    message-group-name: billing-group-test
    order-created-topic: hw35.order.created-billing-test
    payment-succeeded-topic: hw35.payment.succeeded-payment-test
    payment-rejected-topic: hw35.payment.rejected-payment-test
    warehouse-rejected-topic: hw35.warehouse.rejected-payment-test
    delivery-executed-topic: hw35.delivery.executed-payment-test
    delivery-rejected-topic: hw35.delivery.rejected-payment-test

spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/db_otus_35
    username: postgres
    password: postgres
#  flyway:
#    enabled: true
#    schemas: scheme