server:
  port: 8082

payment:
  kafka:
    message-group-name: billing-group
    order-created-topic: hw35.order.created
    billing-succeeded-topic: hw35.billing.succeeded
    billing-rejected-topic: hw35.billing.rejected
    warehouse-rejected-topic: hw35.warehouse.product.reservation.rejected
    delivery-executed-topic: hw35.delivery.executed
    delivery-rejected-topic: hw35.delivery.rejected

spring:
  application:
    name: billing

  datasource:
    url: jdbc:postgresql://my-db-postgresql.default.svc.cluster.local:5432/db_otus_30
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      leak-detection-threshold: 10000
  flyway:
    enabled: true
    schemas: billing_scheme

  kafka:
    bootstrap-servers: my-kafka.default.svc.cluster.local:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    template:
      default-topic: my-topic
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    org:
      apache:
        kafka: OFF



